name: Test
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: List all applications
        run: ls /Applications/
      - name: Use Xcode 12.0.1
        run: sudo xcode-select -switch /Applications/Xcode_12.0.1.app
      - name: Testing Swift package
        run: exec ./.github/scripts/test_swift_package.sh
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh